import {sql} from 'drizzle-orm';
import {
  boolean,
  date,
  datetime,
  decimal,
  int,
  mysqlTable,
  smallint,
  text,
  timestamp,
  varchar,
} from 'drizzle-orm/mysql-core';

export const user = mysqlTable('user', {
  id: varchar('id', {length: 36}).notNull(),
  email: varchar('email', {length: 255}).notNull(),
  username: varchar('username', {length: 50}).notNull(),
  firstName: text('first_name'),
  lastName: text('last_name'),
  dateOfBirth: date('date_of_birth').notNull(),
  gender: int('gender').notNull().default(1),
  phoneNumber: varchar('phone_number', {length: 50}).notNull(),
  address: text('address'),
  height: smallint('height').notNull(),
  profilePic: text('profile_pic'),
  aboutMe: text('about_me'),
  inspiration: text('inspiration'),
  motivation: text('motivation'),
  inspirationImage: text('inspiration_image'),
  motivationImage: text('motivation_image'),
  tags: text('tags'),
  status: varchar('status', {length: 255}).notNull().default('active'),
  created_at: datetime('created_at').notNull().default(new Date()),
  activityLevel: varchar('activity_level', {length: 255})
    .notNull()
    .default('Little to No Movement'),
  premium: boolean('premium').notNull().default(true),
  referral: varchar('referral', {length: 255}).notNull(),
  affiliateId: int('affiliate_id').notNull(),
  verified: boolean('verified').notNull().default(false),
  premium_type: varchar('premium_type', {length: 255}).notNull(),
  password: text('password'),
  resource: varchar('resource', {length: 255}).notNull().default('email'),
  resource_user_id: text('resource_user_id'),
  last_pw_update: timestamp('last_pw_update').notNull(),
  tfa: boolean('tfa').notNull().default(false),
  sdcStartDate: datetime('sdc_start_date').notNull(),
  appDownloadDate: datetime('app_download_date').notNull(),
});

export const food = mysqlTable('food', {
  id: int('id').primaryKey().notNull().autoincrement(),
  nevoId: varchar('nevo_id', {length: 255}).notNull(),
  name: text('name').notNull(),
  description: varchar('description', {length: 245}).default(sql`NULL`),
  serving: decimal('serving', {precision: 10, scale: 2}).default('100'),
  measurementId: int('measurement_id').notNull(),
  foodGroupId: int('food_group_id').notNull(),
  dbType: varchar('db_type', {length: 50}).notNull(),
  suggestable: boolean('suggestable').notNull().default(false),
  image: text('image'),
  nlName: text('nl_name').notNull(),
  passioId: varchar('passio_id', {length: 255}).default(sql`NULL`),
  entityType: varchar('entity_type', {length: 50}).default('item'),
  defaultServing: decimal('default_serving', {precision: 10, scale: 2}).default(
    '100',
  ),
  barcode: varchar('barcode', {length: 100}).default(sql`NULL`),
  isCustom: boolean('is_custom').notNull().default(false),
  userId: varchar('user_id', {length: 36}).default(sql`NULL`),
});
